### ISSUE TITLE
Pop-up not working?

### ISSUE THREAD

**Issue by ptrouw** [Tazzios/pdfviewer#16]
Hi, embed pdf is working great. But the modal pop-up doesn't show anything. I tried to set it in the plug-in and as an additional variable in the article. With debug also no additional information. Using J3.10. Any ideas? Do I have to do anything concerning the modal pop-up?

**Comment by Tazzios** [comment]
Weird, does Joomla debug shows an error?

**Comment by ptrouw** [comment]
Unfortunately no error. I have tried it on 2 different Joomla site. The debug form the plug-in, shows this line:
array(1) { ["file"]=> string(35) "/images/bpt/laatste-nieuws/test.pdf" }

**Comment by ptrouw** [comment]
btw the debug string is the same if I use embed PDF

**Comment by ptrouw** [comment]
If I remove the class="modal", all is fine. Is it a bootstrap thing!
![image](https://user-images.githubusercontent.com/16825488/161947026-ed84ba42-842e-4c73-8bae-1b232ab00fbf.png)

**Comment by Tazzios** [comment]
Do you have other extensions installed that could create the bootstrap problem? Maybe bootstrap is loaded multiple times.

**Comment by ptrouw** [comment]
I don't think so. Perhaps because the template uses "old" BS 3
