### ISSUE TITLE
Pdf preview doesn't appear

### ISSUE THREAD

**Issue by jupagose** [Tazzios/pdfviewer#19]
I'm trying to use but doesn't work but if I use download buttom it shows the PDF, i'm using  `{pdfviewer file=https://domain.com/file.pdf }` syntax.

**Comment by Tazzios** [comment]
I assume you load it from an other domain do you see in the debug console something with:
CORS-header ‘Access-Control-Allow-Origin''  missing or something like that, then it is security related.

**Comment by jupagose** [comment]
Yes U are ok , how can I handle it?

![image](https://user-images.githubusercontent.com/1399739/230725168-044aa87d-0652-4f57-9665-dfd0efcfd3e8.png)

**Comment by Tazzios** [comment]
For me the following worked:
On the webhosting source you need to add the following in the .htaccess 
`Header set Access-Control-Allow-Origin "*"`

Source: https://www.a2hosting.com/kb/developer-corner/enabling-cross-origin-resource-sharing/#Enabling-CORS

**Comment by jupagose** [comment]
But setting Access-Control-Allow-Origin "*" is considered a security risk, what domain must I authorize?

**Comment by Tazzios** [comment]
I guess the domain of your Joomla instance then.

**Comment by jupagose** [comment]
Thanks, I tryied with my own domain but doesn't works, the only way was setting it to *,  does your plugin access external resource to show PDF's ?

**Comment by Tazzios** [comment]
My plugin uses pdfjs what the script does is giving a file to the viewer.html of pdfjs
/plugins/content/pdfviewer/assets/pdfjs/web/viewer.html?file=https%3A%2F%2Fwww.domain.net%2Ftest.pdf

some links that i found:
https://github.com/mozilla/pdf.js/issues/12029
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr

**Comment by jupagose** [comment]
Ok, now is working, Can I use or set some toolbar options to the viewer like use page width view ?

**Comment by Tazzios** [comment]
See the readme, there is a height en width parameter.
To set it global you can set it in the plugin.

**Comment by jupagose** [comment]
Really apreciate your help I'm going to read it carefully. 

Thanjs for all.

**Comment by jupagose** [comment]
At the read-me it specify the PDF's width contaniner but not the PDF itself, It is possible to specify that the pdf always shows in full containers width instead of automatically? 

Actually it shows aas this automatically 

![image](https://user-images.githubusercontent.com/1399739/230729647-fe5424eb-f43a-4bef-8ef1-1b304aa3f903.png)

I want to it shows as this:

![image](https://user-images.githubusercontent.com/1399739/230729667-217561a5-41fb-4b38-a66e-742ee58cd42e.png)

**Comment by Tazzios** [comment]
sorry that is not possible although it seems that pdfjs also has a zoom option that I could build in.
here you can play with it:
https://observablehq.com/@openscience/control-pdf-js-via-iframe-parameter

**Comment by jupagose** [comment]
Great work. Thanks again

**Comment by jupagose** [comment]
A simple last question how to use *Button - pdfviewer*

**Comment by Tazzios** [comment]
If you want to test you can try this new content plugin file. https://github.com/Tazzios/pdfviewer/blob/new-pdfjs-parameters/content_plugin/pdfviewer.php

Release will be later when I have updated pdfjs and the editor button.

**Comment by jupagose** [comment]
Thaaanks ¡!!!! I’m going to try it and going to change my actual PDF plugin

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado: domingo, 9 de abril de 2023 6:24 a. m.
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [Tazzios/pdfviewer] Pdf preview doesn't appear (Issue #19)


If you want to test you can try this new content plugin file. https://github.com/Tazzios/pdfviewer/blob/new-pdfjs-parameters/content_plugin/pdfviewer.php

Release will be later when I have updated pdfjs and the editor button.

**Comment by Tazzios** [comment]
There is a [1.30 beta ](https://github.com/Tazzios/pdfviewer/releases/tag/v1.3.0beta) available for testing.

**Comment by Tazzios** [comment]
[V1.3.0](https://github.com/Tazzios/pdfviewer/releases/tag/v1.3.0) released (identical to the beta)
