### ISSUE TITLE
style popup does not work

### ISSUE THREAD

**Issue by asfonikos** [Tazzios/pdfviewer#25]
Hello,
I have a problem with pdf button in an article, popup is blank. My Joomla version is 4.2.9.
Thank you.

![pdf_viewer_error](https://user-images.githubusercontent.com/40475514/233436348-ec12e04a-c510-45fb-afea-84a9cbfb1827.PNG)

**Comment by Tazzios** [comment]
That is not much information to go on. What is the exact tag that you are using? Does embed or new works?

**Comment by Tazzios** [comment]
Ok, did some testing: it seems the Joomla 4 modal popup works different then in Joomla3. The modal popup is not working since the beginning. 
So I will note it as a bug and look in to it.

**Comment by asfonikos** [comment]
First of all congratulations for your great job. This plugin is very good and works perfect in Joomla3. I just wanted to let you know what I found out in joomla4. If you write the link code inside article editor works fine. Just the modal popup is not working for me.Thank you for your answers.  Sent from Mail for Windows From: TazziosSent: Πέμπτη, 20 Απριλίου 2023 9:14 μμTo: Tazzios/pdfviewerCc: asfonikos; AuthorSubject: Re: [Tazzios/pdfviewer] PDF Button (Issue #25) Ok, did some testing: it seems the Joomla 4 modal popup works different then in Joomla3. The modal popup is not working since the beginning.So I will note it as a bug and look in to it.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by asfonikos** [comment]
First of all congratulations for your great job. This plugin is very good and works perfect in Joomla3. I just wanted to let you know what I found out in joomla4. If you write the link code inside article editor works fine. Just the modal popup is not working for me.
Thank you for your answers.

**Comment by Tazzios** [comment]
Did you copied it from the correct branch and to the right location?
Anyway, here is a build that (should) work for j3 and j4
https://github.com/Tazzios/pdfviewer/releases/tag/v1.3.1

**Comment by Tazzios** [comment]
@asfonikos does v1.3.1  works for you? Then i could close this issue.

**Comment by marpyth** [comment]
Same problem here: when clicking the PDF button in the article editor, the pop up is completely empty.
In V 1.3.1 package there is no editor by the way, so you first have to install 1.3.0, and then update the pdf content plugin to 1.3.1. Button version remains 1.3.0
The pdf viewer generally works perfect in the website. Thansk!

**Comment by Tazzios** [comment]
content pdfviewer popup works in J4

**Comment by Tazzios** [comment]
ah, I missed that this was also about the Button instead of the content plugin.

- So content popup is fixed.
- Button popup is open at #29

**Comment by asfonikos** [comment]
I have the same problem with @marpyth. Otherwise the pdf viewer works fine. Thank you.
