### ISSUE TITLE
PDF won't load after updating extension

### ISSUE THREAD

**Issue by jstoval** [Tazzios/pdfviewer#28]
Hello,
Thank you for this extension... best PDF viewer for Joomla I've ever used by far.  Version 1.2.5 was working great on my sites.  I updated to version 1.3, and now the PDF won't load.  Here is the error code from Firefox Inspector Console.  I'm running Joomla 4.3.1.

Uncaught (in promise) TypeError: element is null
    _bindListeners viewer.js:14077
    Toolbar viewer.js:14025
    _initializeViewerComponents app.js:1086
    initialize app.js:687

**Comment by Tazzios** [comment]
Error is unkown but seems related to the pdfjs viewer.
The browser is sometimes too aggressive with the caching from pdf.js. After a from pdf.js it some times gives problems. Does it work in private browser mode?

There is also a v1.3.1 version.

**Comment by marpyth** [comment]
Just tried a private tab: no succes. same empty popup

![image](https://user-images.githubusercontent.com/111567426/236680551-f706c626-e0a8-405a-8d93-7e74f100ad07.png)

**Comment by Tazzios** [comment]
Are you talking about the button or the content plugin?
For button it is probably this problem: #29

**Comment by marpyth** [comment]
It’s the button plugin which opens a blank pop-up in the editor in joomla 4 backend The content plugin (i guess this takes care that the pdf is shown at the front end of the website) works perfect Met vriendelijke groet,Martijn SmitOp 7 mei 2023 om 16:10 heeft Tazzios ***@***.***> het volgende geschreven:﻿
Are you talking about the button or the content plugin?
For button it is probably this problem: #29

**Comment by Tazzios** [comment]
same as #29
