### ISSUE TITLE
db string hardcoded

### ISSUE THREAD

**Issue by SchwielowNET** [Tazzios/pdfviewer#30]
Hello,
in the pdfviewer.php lines 439, 444 and 449 is the path to the jdownload tables hardcoded (josmf_jdownloads_categories). If an user use an other prefix for the joomla-tables, he get an error while display a pdf. I changed the 3 entrys with my prefix, but I fear that this will be reset after an update. Please change the code, so it works with any installations with random prefix.
Many thanks
Micha

**Comment by Tazzios** [comment]
oeps, That is nasty!
I see that it went wrong in 1.3.1 in the 1.30 it still was correct. This query only effects the pdf to image function, looks like it is not so much used.

If you replace 'josmf' with '#_' your safe, example:
'josmf_jdownloads_categories'
to
'#__jdownloads_categories' ( so 2 underscores in total)

I will make a new release which will do the same.

**Comment by SchwielowNET** [comment]
Yes, you are right... with #__ as prefix it works also. Many thanks for your work.
PS: Your pdf to image function is the unique selling point that distinguishes your plugin from others.

**Comment by Tazzios** [comment]
V1.3.2 Released. also found another bug an updated PDF.js
