### ISSUE TITLE
updates_plugin.xml points to 404 for version 1.3.2

### ISSUE THREAD

**Issue by webenhanced** [Tazzios/pdfviewer#31]
When attempting to update the plugin to 1.3.2 in Joomla 4 (latest), we get an "Error connecting to the server: 404". Copying the download url from the xml file results in a 404 not found.

Download URL in xml:-
https://github.com/Tazzios/pdfviewer/releases/download/v1.3.2/pdfviewer_content_1.3.2.zip

From github releases, it should be:-
https://github.com/Tazzios/pdfviewer/releases/download/V1.3.2/pdfviewer_content_1.3.2.zip

Note the case difference on v1.3.2

**Comment by Tazzios** [comment]
Changed it to a Capital in the xml, renaming the release did not work.
