### ISSUE TITLE
[Joomla 5] Disabling of plg_behaviour_compat plugin leads to Class "JPlugin" not found error

### ISSUE THREAD

**Issue by FrankReisenhofer** [Tazzios/pdfviewer#33]
Hello all together,

When trying to disable the plg_behaviour_compat plugin in Joomla 5 i get the following error: [1]

Looks like Joomla 5 is not yet supported fully by the pdfviewer.

Do you have any plans to support Joomla 5 completely?

Thanks for some feedback.

[1]

An error has occurred.
0 Class "JPlugin" not found
Call Stack
#	Function	Location
1	()	JROOT/plugins/content/pdfviewer/pdfviewer.php:15

**Comment by FrankReisenhofer** [comment]
https://github.com/Tazzios/pdfviewer/pull/34 should solve this issue

**Comment by Tazzios** [comment]
I have created an 1.4.0 for J5. When upgrading to J5 the update will be shown.
