### ISSUE TITLE
Disable download in the Tools menu

### ISSUE THREAD

**Issue by mynter** [Tazzios/pdfviewer#9]
Is there an easy way to disable the Download menu item in the Tools menu? Where can I modify code to achieve this?

**Comment by mynter** [comment]
I was a bit quick to ask the question....  I removed the Download item by putting this in the viewer.css file:

.download
{
    display:none !important;
}

**Comment by Tazzios** [comment]
That is an other way then that i used. :)

In the 'viewer.html' file you need to at the class 'hidden' to the two download buttons.
Use the 'Override pdfjs' function if you not want to edit this at every update. You can find it at the end of the readme. This means you have to update PDFJS by yourself once in a while.

Hiding the download button is only cosmetic, the pdf file is already on the user computer and the link to the file you can find in the html code.

**Comment by mynter** [comment]
Thanks for the quick answer/comments :-) I think most of my users are not technical enough to realize it is on their computer already...  Very neat plugin. It is very helpful for my project.
